spring:
  application:
    name: car-rental-system
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/carrentaldb
    username: postgres
    password: postgres
